version: '3'
services: 
    aqi-api:
        build: .
        ports: 
            - "8080:80"
            - "8081:443"
        environment: 
            ASPNETCORE_URLS: "https://+;http://+"
            ASPNETCORE_HTTPS_PORT: "8081" 
            ASPNETCORE_ENVIRONMENT: "Development"
        volumes: 
            - $***REMOVED***APPDATA***REMOVED***\microsoft\UserSecrets\:/root/.microsoft/usersecrets
            - $***REMOVED***USERPROFILE***REMOVED***\.aspnet\https:/root/.aspnet/https/