image: "mcr.microsoft.com/dotnet/core/sdk:3.1"

stages:
  - build
  - test
  - publish
  - deploy

variables:
  PUBLISHDIR: "bin/release/"

before_script:
  - "cd Data/AirQi/"
  - "dotnet restore"

build:
  stage: build

  script:
      - "dotnet build AirQi.sln"
    
test:
  stage: test

  script:
    - "dotnet test AirQi.sln"

publish:
  stage: publish

  when: manual

  script:
    - echo "Publish the web application"
  # only:
  #   - master

deploy:
  stage: deploy
  
  when: manual
  
  script:
    - echo "Deploy to production"
  # only:
  #   - master
