image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - core
  - data
  - test

core:
  stage: Base API

  script:
    - "cd Core/ApiBase"
    - "dotnet build"

data:
  stage: Data API

  script:
    - "cd Data/AirQi"
    - "dotnet build"

test:
  stage: test

  script:
    - "cd Core"
    - "dotnet test"
