image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - data
  - data.tests

  - core
  - core.tests

core:
  stage: core

  script:
    - "cd Core/ApiBase"
    - "dotnet build"

core.tests:
  stage: core.tests

  script:
    - "cd Core"
    - "dotnet test"

data:
  stage: data

  script:
    - "cd Data/AirQi"
    - "dotnet build"

data.tests:
  stage: data.tests

  script:
    - "cd Data/AirQi"
    - "dotnet test"