image: microsoft/dotnet:latest

stages:
  - build
  - test
  - publish
  - deploy

build:
  stage: build

  script:
    - dotnet build 
    # - cd ../Core/ApiBase"
    # - dotnet build
  # only:
  #   - master

  artifacts:
    paths:
      - Data/AirQi
    

test:
  stage: test

  script:
    - dotnet test
    # - cd ../Core
    # - dotnet test
  # only:
  #   - master

  artifacts:
    paths:
      - Data/AirQi/Tests

publish:
  stage: publish

  script:
    - echo "Publish the web application"
  # only:
  #   - master

deploy:
  stage: deploy
  
  # when: manual
  
  script:
    - echo "Deploy to production"
  # only:
  #   - master
