stages:
    - build
    
docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - "cd WebAPI"
    - docker login -u pepsm -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t index.docker.io/pepsm/webapi .
    - docker push index.docker.io/pepsm/webapi
 