image: mcr.microsoft.com/dotnet/core/sdk:5

stages:
  - data
  - datatests
  - core
  - coretests

core:
  stage: core

  script:
    - "cd Core/ApiBase"
    - "dotnet build"

coretests:
  stage: coretests

  script:
    - "cd Core"
    - "dotnet test"

data:
  stage: data

  script:
    - "cd Data/AirQi"
    - "dotnet build"

datatests:
  stage: datatests

  script:
    - "cd Data/AirQi"
    - "dotnet test"