image: microsoft/dotnet:latest

stages:
  - build
  - test
  - publish
  - deploy

build:
  stage: build

  script:
    - cd Data/AirQi
    - dotnet build
    # - cd ../Core/ApiBase"
    # - dotnet build
  # only:
  #   - master

test:
  stage: test

  script:
    - cd Data/AirQi
    - dotnet test
    # - cd ../Core
    # - dotnet test
  # only:
  #   - master

publish:
  stage: publish

  script:
    - echo "Publish the web application"
  # only:
  #   - master

deploy:
  stage: deploy
  when: manual
  script:
    - echo "Deploy to production"
  # only:
  #   - master
