image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - core
  - test
  - unit
  - publish
  - deploy

build:
  stage: build

  script:
    - "cd Data/AirQi"
    - "dotnet build"
core:
  stage: core

  script:
    - "cd Core/ApiBase"
    - "dotnet build"

test:
  stage: test

  script:
    - "cd Data/AirQi"
    - "dotnet test"

unit:
  stage: unit

  script:
    - "cd Core"
    - "dotnet test"

publish:
  stage: publish

  when: manual

  script:
    - echo "Publish the web application"
  # only:
  #   - master

deploy:
  stage: deploy

  when: manual

  script:
    - echo "Deploy to production"
  # only:
  #   - master
