apiVersion: apps/v1
kind: Deployment
metadata:
  name: marker-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: markerservice
  template:
    metadata:
      labels:
        app: markerservice
    spec:
      containers:
        - name: markerservice
          image: pepsm/markerservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: markerservice-clusterip
spec:
  type: ClusterIP
  selector:
    app: markerservice
  ports:
  - name: markerservice
    protocol: TCP
    port: 80
    targetPort: 8082