apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-auth-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-auth-deployment
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: auth-service
          image: mcr.microsoft.com/mssql/server:latest
          ports:
            - containerPort: 1433
          env:
          - name: MSSQL_PID
            value: "Express"
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql
                key: SA_PASSWORD
          volumeMounts:
          - mountPath: /var/opt/mssql/data
            name: auth-service
      volumes:
      - name: auth-service
        persistentVolumeClaim:
          claimName: mssql-auth-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-auth-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 1434
    targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-auth-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 1434
    targetPort: 1433